#!/usr/bin/env bash

ip=${1-sedsdaq.ecn.purdue.edu}

# ssh root@$ip "nohup /var/lib/fsw > /dev/null 2>&1 < /dev/null &"
# ssh root@$ip "nohup /var/lib/fsw_telemetry_server > /dev/null 2>&1 < /dev/null &"

WINDOW_NAME="Avi Client"

tmux new-window -n "$WINDOW_NAME" \
     "python3 -m gse.command"

tmux split-window -h \
     "python3 -m gse.bangbang"

tmux split-window -h \
     "python3 -m gse.telem"

tmux select-window -t "$WINDOW_NAME"
