import struct

PT_ZEROING_TARGET = 14.7

PT_OX_201_ZERO_OFFSET = 0
PT_FU_201_ZERO_OFFSET = 0
PT_HE_201_ZERO_OFFSET = 0

ADC_V_SLOPE  =  0.00000000235714724017
ADC_V_OFFSET = -0.01390133824020600000

AVI_CMD_PORT   = 2703
AVI_TELEM_PORT = 2702
SYNNAX_PORT    = 9090

SYNNAX_IP = '192.168.2.59'
AVI_IP    = '192.168.2.110'

SYNNAX_USERNAME = "Bill"
SYNNAX_PASSWORD = "Bill"

TELEM_FORMAT = '<QQQ'
TELEM_STRUCT = struct.Struct(TELEM_FORMAT)
TELEM_SIZE   = TELEM_STRUCT.size

LOX_CHANNEL_NAME     = 'PT_OX_201'
FUEL_CHANNEL_NAME    = 'PT_FU_201'
HELIUM_CHANNEL_NAME  = 'PT_HE_201'
BB_OPEN_CHANNEL_NAME = 'BB_OPEN_ALL_CMD'
BB_ISO_CHANNEL_NAME  = 'BB_ISO_ALL_CMD'
BB_REG_CHANNEL_NAME  = 'BB_REG_ALL_CMD'
BB_FU_UPPER_SETP_NAME = 'SET_FU_UPPER_SETP_cmd'
BB_OX_UPPER_SETP_NAME = 'SET_OX_UPPER_SETP_cmd'
BB_FU_LOWER_SETP_NAME = 'SET_FU_LOWER_SETP_cmd'
BB_OX_LOWER_SETP_NAME = 'SET_OX_LOWER_SETP_cmd'
BB_FU_UPPER_REDLINE_NAME = 'SET_FU_UPPER_REDLINE_cmd'
BB_OX_UPPER_REDLINE_NAME = 'SET_OX_UPPER_REDLINE_cmd'
BB_FU_LOWER_REDLINE_NAME = 'SET_FU_LOWER_REDLINE_cmd'
BB_OX_LOWER_REDLINE_NAME = 'SET_OX_LOWER_REDLINE_cmd'

FUEL_SOLENOID_NAME = 'SV_HE_202'
LOX_SOLENOID_NAME  = 'SV_HE_201'
