#!/usr/bin/bash

WINDOW_NAME="Mock Avi"

tmux new-window -n "$WINDOW_NAME" \
     "python3 -m gse.mock.test_tlm_server"

tmux split-window -h \
     "python3 -m gse.mock.test_cmd_server"

sleep 0.1

./run

# tmux select-window -t "$WINDOW_NAME"
