cc_library(
    name = "net",
    srcs = [
        "cms.cpp",
    ],
    hdrs = [
        "cms.hpp",
    ],
    deps = [
        "@nlohmann_json//:json",
    ],
    visibility = ["//visibility:public"],
)
